name: Daily Fetch Cron Job

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py

      - name: Configure Git
        run: |
          git config --local user.email "sabiyyuhakim@gmail.com"
          git config --local user.name "SulthanAbiyyu"

      - name: Add and commit changes
        run: |
          git add valid_proxies.txt
          STATUS=$(git status --porcelain | wc -l)
          echo "number of files that need to be committed: $STATUS"
          if [ $STATUS -gt 0 ]; then
            now=$(date)
            git commit -m "Auto Commit $now"
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
